import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Breadcrumb from "@/components/breadcrumb/Breadcrumb";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};


import SideNavbar from "@/components/partials/navbar/sideNavbar/SideNavbar";
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} grid grid-cols-[auto_1fr] min-h-screen`}>
                <SideNavbar/>
                <div>
                    <Breadcrumb/>
                    {children}
                </div>
            </body>
		</html>
	);
}
