"use client"
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Breadcrumb from "@/components/breadcrumb/Breadcrumb";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// };


import SideNavbar from "@/components/partials/navbar/sideNavbar/SideNavbar";
import { useState } from "react";
export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
    const [isSidebarOpen,setIsSidebarOpen] = useState(false)
	return (
		<html lang="en">
			<body className={`${inter.className} grid grid-cols-[auto_1fr] min-h-screen`}>
                <SideNavbar setIsSidebarOpen={setIsSidebarOpen} className={`${isSidebarOpen?"translate-x-[0%]":"-translate-x-full"} md:translate-x-[0%] transition-transform duration-200 w-64 fixed top-0 bottom-0`}/>
                <div className="md:pl-64 transition-[padding] duration-200">
                    <div onClick={()=>setIsSidebarOpen(true)}>toggle</div>
                    <Breadcrumb/>
                    {children}
                </div>
            </body>
		</html>
	);
}
