import Hero from "@/components/template/ecommerce/main/hero/Hero"

export default function page() {
    return (
        <main>
            <Hero/>
            <section>Flash Sale</section>
            <section>Browse By Category</section>
            <section>Best selling Products</section>
            {/* <section>Featured Products</section> */}
            <section>Explore Our Products</section>
            <section>New Arrival</section>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quod tempora quisquam hic natus molestiae vitae suscipit at nobis optio fugiat, libero ipsam tenetur dolore provident eveniet sapiente obcaecati blanditiis voluptatibus labore iusto molestias. Hic magnam consequuntur perferendis numquam magni ex nam ut libero labore quas, aperiam suscipit officiis eius, error minus doloribus inventore eligendi tempore voluptate dignissimos ipsa. Quia placeat quisquam asperiores vero iure nobis, autem quidem reprehenderit, cumque porro nostrum fuga molestiae numquam itaque. Maxime dolor, sint, cupiditate veniam at rerum in harum libero, accusantium totam distinctio enim neque quaerat! Nam iusto eum nostrum omnis autem consequatur ipsam vero.</div>
        </main>
    );
}
